-- Auto-assign stable numeric IDs to localities for easier reuse.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'localities'
      AND column_name = 'public_id'
  ) THEN
    ALTER TABLE public.localities
      ADD COLUMN public_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

    ALTER TABLE public.localities
      ALTER COLUMN public_id SET NOT NULL;

    ALTER TABLE public.localities
      ADD CONSTRAINT localities_public_id_key UNIQUE (public_id);
  END IF;
END
$$;
